import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "CS22 Web Blog",
  description: "Generated by create next app",
  icons:{
    icon: "aclc.png"
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body className={`${roboto.className} bg-[#F6F6F6] select-none overflow-x-hidden` }>{children}</body>
    </html>
  );
}
